name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build with esbuild
        run: node esbuild.config.js

      - name: Debug dist directory
        run: |
          ls -lh dist/

      - name: Package for Windows
        run: npx pkg -t node18-win-x64 -o dist/pralaya-db-windows dist/cli.cjs

      - name: Package for Linux
        run: npx pkg -t node18-linux-x64 -o dist/pralaya-db-linux dist/cli.cjs

      - name: Package for macOS
        run: npx pkg -t node18-macos-x64 -o dist/pralaya-db-macos dist/cli.cjs

      - name: Compress Windows executable
        run: |
          if [ -f dist/pralaya-db-windows.exe ]; then
            zip -r artifacts/pralaya-db-windows.zip dist/pralaya-db-windows.exe
          else
            echo "Windows executable not found. Skipping compression."
            exit 1
          fi

      - name: Compress Linux executable
        run: zip -r artifacts/pralaya-db-linux.zip dist/pralaya-db-linux

      - name: Compress macOS executable
        run: zip -r artifacts/pralaya-db-macos.zip dist/pralaya-db-macos

      - name: Upload release artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pralaya-db-executables
          path: |
            artifacts/pralaya-db-windows.zip
            artifacts/pralaya-db-linux.zip
            artifacts/pralaya-db-macos.zip
