name: Build and Release

on:
  push:
    tags:
      - 'v*' # Trigger workflow on version tags (e.g., v1.0.0)

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build executables
        run: |
          node esbuild.config.js
          npx pkg --targets node18-linux -o dist/pralaya-db-linux dist/cli.cjs
          npx pkg --targets node18-macos -o dist/pralaya-db-macos dist/cli.cjs
          npx pkg --targets node18-windows -o dist/pralaya-db-windows.exe dist/cli.cjs

      - name: Create artifacts directory
        run: mkdir -p artifacts

      - name: Compress executables
        run: |
          zip -r artifacts/pralaya-db-linux.zip dist/pralaya-db-linux
          zip -r artifacts/pralaya-db-macos.zip dist/pralaya-db-macos
          zip -r artifacts/pralaya-db-windows.zip dist/pralaya-db-windows.exe

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/pralaya-db-linux.zip
            artifacts/pralaya-db-macos.zip
            artifacts/pralaya-db-windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
